export default {
  SAVE_UID: "SAVE_UID",
  CLEAR_UID: "CLEAR_UID",
  ADD_DOCUMENT: "ADD_DOCUMENT",
  DELETE_DOCUMENT: "DELETE_DOCUMENT",
  SET_ERROR_MSG: "SET_ERROR_MSG",
  CLEAR_ERROR_MSG: "CLEAR_ERROR_MSG",
};
